- name: Setup rtags
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Install dependencies
      become: yes
      apt:
        pkg:
          - llvm-dev
          - libclang-dev
    - name: Clone rtags
      git:
        repo: https://github.com/Andersbakken/rtags.git
        dest: /home/{{ ansible_ssh_user }}/src/rtags
        update: no
    - name: Configure rtags
      shell: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
      args:
        chdir: /home/{{ ansible_ssh_user }}/src/rtags
    - name: Build rtags
      make:
        chdir: /home/{{ ansible_ssh_user }}/src/rtags
        params:
          NUM_THREADS: 16
    - name: Install company
      shell: emacs -batch -Q --eval="(package-install \"company\")"
